preprocessing:
  input_data_path: ./data/train.csv
  test_data_path: ./data/test.csv
  input_text: comment_text
  split_ratio: 0.2
  random_state: 0
  test_id: id
  max_len: 128
  text_converter: neural_network_vecterization
  embedding_col: 100
  pretrained_embedding: ./data/glove.twitter.27B.100d.txt
training:
  model_name: text_cnn
  batch_size: 32
  dropout: 0.5
  embedding_col: 100
  max_len: 128
  optimizer: sgd
  epochs: 2
predict:
  output_path: ./data/submission_pretrained_embedding.csv
